config/routes.rb
Rails.application.routes.draw do
  get 'favourites/update'
  root 'home#index'

  resources :properties do
    member do
      get :approve
    end
    # collection do
    #   patch 'approve'
    # end
    resources :reviews
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :categories, except: [:show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'properties/approve_property'
  # post 'properties/:id', to: 'properties#approve'
# delete 'sign_out', to: "sessions#destroy", as: 'sign_out'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  after_validation { self.name = self.name.capitalize }
  validates :name, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :property
  belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_one_attached :property_image
  has_many :reviews, dependent: :destroy

  after_validation { self.city = self.city.upcase }

  validates :address, presence: true, length: {minimum: 10, maximum: 255}
  validates :Price, presence: true, numericality: true
  validates :Area, presence: true, numericality: true
  validates :OwnerName, presence: true, length: {minimum: 3, maximum: 50}
  validates :ContactPerson, presence: true, length: {minimum: 3, maximum: 50}
  validates :Number, presence: true, numericality: true, length: { is: 10 }
  validates :city, presence: true
  validates :property_status, presence: true
end
# y(id: integer, PropertyType: string, address: string, Price: float, Area: float,
#    OwnerName: string,
#    ContactPerson: string, Number: integer, user_id: integer,
#    created_at: datetime, updated_at: datetime,
#     city: string, property_status: string, approved_status: boolean,
#      rejection_reason: string)

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :property
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  has_many :properties, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites

  after_validation { self.email = self.email.downcase }

  validates :username, presence: true, length: { maximum: 25 }, uniqueness: { case_sensetive: false }
  validates :email, presence: true, length: { maximum: 25 }, uniqueness: { case_sensetive: false }, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :admin?, :favourite_text

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def admin?
    if logged_in?
      current_user.admin
    end
  end

  def favourite_text
    return @favourite_exists ? "Unfavourite" : "Favourite"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end
  def new
    @category = Category.new
  end
  def edit
    @category = Category.find(params[:id])
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category is Add Successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category is Updated Successfully"

      redirect_to categories_path
    else
      render 'edit'
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] = "Category is Deleted"

    redirect_to categories_path
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def update
    favourite = Favourite.where(property: Property.find(params[:property]), user: current_user)
    if favourite == []
      Favourite.create(property: Property.find(params[:property]), user: current_user)
      @favourite_exists = true
    else
      favourite.destroy_all
      @favourite_exists = false
    end
    redirect_to property_path(Property.find(params[:property]))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @property_first = Property.first(3)
    @property_last = Property.order("created_at DESC").last(3)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    if admin?
      @property = Property.where(approved_status: 'false').order('created_at DESC')
    else
      @property = Property.where(approved_status: 'true')
    end
  end

  def new
    @property = Property.new
  end
  def approve
    @property = Property.find(params[:id])
    if @property.update(approved_status: "true")
      flash[:notice] = "New property approved"
      redirect_to properties_path
    end
  end
  def show
    @property = Property.find(params[:id])
    @favourite_exists = Favourite.where(property: @property,user: current_user) == [] ? false : true
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to @property
    else
      render 'edit'
    end
  end

  def create
    @property = Property.new(property_params)
    @property.user = User.first
    if @property.save
      redirect_to @property
    else
      render 'new'
    end
  end

  private
    def property_params
      params.require(:property).permit(:PropertyType, :property_status, :address, :city, :Price, :Area, :OwnerName, :ContactPerson, :Number, :property_image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.create(review_params)
    @review.user_id = current_user.id
    @review.save

    redirect_to property_path(@property)
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in Successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end


  def edit
    
  end

  def show

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "BOOYAH #{@user.username}"
      redirect_to properties_path
    else
      render 'new'
    end
  end

  def update

    if @user.update(user_params)
      flash[:notice] = 'ACCOUNT IS UPDATED'
      redirect_to properties_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  def set_user
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<table class="ui collapsing table">
  <thead>
    <tr>
      <th ></th>
      <th class="ten wide">Category</th>
      <th class=""colspan="3">Links</th>
    </tr>
  </thead>
  <tbody>
    <% @category.each_with_index do |category,i| %>

    <tr>
      <td><%= i+1 %> .</td>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1 class="text-center" >Create Property</h1>
<%= render 'shared/errors',obj: @category %>

<%= form_with(model: @category, html: {class: "ui large form"}, local: true) do |form| %>
  <h4 class="ui dividing header">Property Information</h4>
    <div class="field">
    <label> <%= form.label :name, "Contact Number" %></label>
    <div class="fields">
      <div class="twelve wide field">
        <%= form.text_field :name,placeholder: "Categories", class: "border border-success" %>
      </div>
    </div>
  </div>

  <%= form.submit @category.new_record? ? 'SAVE' : 'UPDATE', class: "ui green button" %>
<% end %>

app/views/favourites/update.js.erb
$('#favourite_link').text("<%= favourite_text %>");

app/views/home/index.html.erb
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="3000">
      <%= image_tag("carousel_image_1.jpg",height: "400px", class: "d-block w-100")%>
    </div>
    <div class="carousel-item" data-interval="3000">
      <%= image_tag("carousel_image_2.jpg",height: "400px", class: "d-block w-100")%>
    </div>
    <div class="carousel-item" data-interval="3000">
      <%= image_tag("carousel_image_3.jpg",height: "400px", class: "d-block w-100")%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h1 class="text-center">Hand Picked Projects For You</h1>

<div class="ui divided items">
<% @property_first.each do |property| %>
  <div class="item">
    <div class="image">
      <% if property.property_image.attached? %>
        <%= image_tag(property.property_image)%>
      <% end %>
    </div>
    <div class="content">
      <%= link_to property.PropertyType, property, class: "header" %>
      <div class="meta">
        <span class="home">By <%= property.OwnerName %></span><br/>
        <span class="home">Posted <%= time_ago_in_words(property.created_at) %></span>
      </div>
      <div class="description">
        <p></p>
      </div>
      <div class="extra">
        <div class="ui label"><i class="home icon"></i><%= property.property_status%></div>
        <span class="home text-dark"><i class="rupee sign icon green"></i><%= property.Price%></span>
        <div class="ui right floated primary button">
          <%= link_to "Show Details", property ,class: "text-white"%>
          <i class="right chevron icon"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>
<h1 class="text-center">Recently Added Products</h1>

<div class="ui divided items">
<% @property_last.each do |property| %>
  <div class="item">
    <div class="image">
      <% if property.property_image.attached? %>
        <%= image_tag(property.property_image)%>
      <% end %>
    </div>
    <div class="content">
      <%= link_to property.PropertyType, property, class: "header" %>
      <div class="meta">
        <span class="home">By <%= property.OwnerName %></span><br/>
        <span class="home">Posted <%= time_ago_in_words(property.created_at) %></span>
      </div>
      <div class="description">
        <p></p>
      </div>
      <div class="extra">
        <div class="ui label"><i class="home icon"></i><%= property.property_status%></div>
        <span class="home text-dark"><i class="rupee sign icon green"></i><%= property.Price%></span>
        <div class="ui right floated primary button">
          <%= link_to "Show Details", property ,class: "text-white"%>
          <i class="right chevron icon"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/_form.html.erb
<%= form_with(model: @property, html: {class: "ui large form"}, local: true) do |form| %>
  <h4 class="ui dividing header">Property Information</h4>
  <div class="two fields">
    <div class="field">
      <%= form.label :PropertyType, "Property Type" %>
      <%= form.select :PropertyType, options_from_collection_for_select(Category.all, :name, :name, form.object.PropertyType), :prompt => 'Property Type',class: "ui fluid dropdown" %>
    </div>
    <div class="field">
      <%= form.label :property_status, "Property Status" %>
      <%= form.select :property_status, [ 'Rental', 'Sold', 'Sale' ], :prompt => 'Property Status',class: "ui fluid dropdown" %>
    </div>
  </div>

  <div class="field">
    <label> <%= form.label :address, "Address" %></label>
    <div class="fields">
      <div class="twelve wide field">
         <%= form.text_field :address, placeholder: "Address", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label><%= form.label :OwnerName, "Owner Name" %></label>
    <div class="fields">
      <div class="twelve wide field">
        <%= form.text_field :OwnerName, placeholder: "Owner Name", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label><%= form.label :city, "City" %></label>
    <div class="fields">
      <div class="twelve wide field">
         <%= form.text_field :city, placeholder: "City", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label><%= form.label :Price, "Price" %></label>
    <div class="fields">
      <div class="twelve wide field">
        <%= form.text_field :Price, placeholder: "Amount in INR (eg. 12000 )", class: "border border-success" %>
       </div>
    </div>
  </div>
  <div class="field">
    <label> <%= form.label :Area, "Area" %></label>
    <div class="fields">
      <div class="twelve wide field">
        <%= form.text_field :Area, placeholder: "Area in sqft", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label> <%= form.label :ContactPerson, "Contact Person" %></label>
    <div class="fields">
      <div class="twelve wide field">
         <%= form.text_field :ContactPerson,placeholder: "Contact Person", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label> <%= form.label :Number, "Contact Number" %></label>
    <div class="fields">
      <div class="twelve wide field">
        <%= form.text_field :Number,placeholder: "Number without 0 or +91 (eg. 89xxxxxxxx )", class: "border border-success" %>
      </div>
    </div>
  </div>
  <div class="field">
    <label><%= form.label :property_image, "Property Image" %></label>
    <%= form.file_field :property_image, class: "border border-success ui button" %>
  </div>

  <%= form.submit @property.new_record? ? 'SAVE' : 'UPDATE', class: "ui green button"%>
<% end %>

app/views/properties/edit.html.erb
<h1 class="text-center" >Edit Property</h1>
<%= render 'shared/errors',obj: @property %>
<%= render 'form'%>

app/views/properties/index.html.erb
<h1 class="text-center">All Properties</h1>
<div class="ui divided items">
<% @property.each do |property| %>
  <div class="item">
    <div class="image">
      <% if property.property_image.attached? %>
        <%= image_tag(property.property_image)%>
      <% end %>
    </div>
    <div class="content">
      <%= link_to property.PropertyType, property, class: "header" %>
      <div class="meta">
        <span class="home">By <%= property.OwnerName %></span><br/>
        <span class="home">Posted <%= time_ago_in_words(property.created_at) %></span>
      </div>
      <div class="description">
        <p></p>
      </div>
      <div class="extra">
        <div class="ui label"><i class="home icon"></i><%= property.property_status%></div>
        <span class="home text-dark"><i class="rupee sign icon green"></i><%= property.Price%></span>

        <div class="ui right floated primary button">
          <%= link_to "Show Details", property ,class: "text-white"%>
          <i class="right chevron icon"></i>
        </div>
        <div class="ui right floated primary button">
          <%= link_to "Approve", approve_property_path(property) ,class: "text-white"%>
          <i class="right chevron icon"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/new.html.erb
<h1 class="text-center">Post Property</h1>
<%= render 'shared/errors',obj: @property %>
<%= render 'form'%>

app/views/properties/show.html.erb
<h1 class="text-center">SHOW</h1>

<% if @property.property_image.attached? %>
  <%= image_tag(@property.property_image, width: 400, height: 400)%>
<% end %>
<table>
  <thead>
    <th>Property Type</th>
    <th>Property Status</th>
    <th>Address</th>
    <th>City</th>
    <th>Price</th>
    <th>Area</th>
    <th>Owner Name</th>
    <th>Contact person</th>
    <th>Number</th>
    <th>Links</th>
  </thead>

  <tbody>
    <tr>
      <td><%= @property.PropertyType %></td>
      <td><%= @property.property_status %></td>
      <td><%= @property.address %></td>
      <td><%= @property.city %></td>
      <td><%= @property.Price %></td>
      <td><%= @property.Area %></td>
      <td><%= @property.OwnerName %></td>
      <td><%= @property.ContactPerson %></td>
      <td><%= @property.Number %></td>
      <td><%= link_to 'Edit',edit_property_path(@property) %></td>
    </tr>
  </tbody>
</table>
<%= link_to favourite_text, favourites_update_path(property: @property), id: 'favourite_link'%>
<% if @favourite_exists == true %>
  <p>Favourite Exists</p>
<% end %>
<h2>Reviews</h2>
<% @property.reviews.each do |review| %>
  <p>
    <strong>Ratings:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>
<% end %>
<h2>Add a comment:</h2>
<%= form_with model: [ @property, @property.reviews.build ], local: true do |form| %>
  <p>
    <%= form.label :rating %><br>
    <%= form.text_field :rating %>
  </p>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, html: {class: "ui form"}, local: true) do |form| %>
  <div class="field">
    <span class = "font-weight-bold"><%= form.label :username, "Username"%></span>
    <span class = "text-danger">*</span>
    <%= form.text_field :username, placeholder: "Username", class: "border border-success"%>
  </div>
  <div class="field">
    <span class = "font-weight-bold"><%= form.label :email, "Email"%></span>
    <span class = "text-danger">*</span>
    <%= form.email_field :email, placeholder: "Email", class: "border border-success"%>

  </div>
  <div class="field">
    <span class = "font-weight-bold"><%= form.label :password, "Password"%></span>
    <span class = "text-danger">*</span>
    <%= form.password_field :password, placeholder: "Password", class: "border border-success"%>
  </div>
  <div class="field">
    <span class = "font-weight-bold"><%= form.label :password, "Password"%></span>
    <span class = "text-danger">*</span>
    <%= form.password_field :password_confirmation, placeholder: "Password Confirmation", class: "border border-success"%>
  </div>
  <%= form.submit @user.new_record? ? 'SIGN UP' : 'UPDATE', class: "ui button green"%>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">EDIT <%= @user.class %></h1>
<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center">Sign UP</h1>
<%= render 'shared/errors', obj: @user %>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center">HELLO, <%= @user.username %></h1>
<h1>Favourite</h1>
<% current_user.favourites.each do |favorite| %>
  <p><%= favorite.property.city %></p>
<% end %>