config/routes.rb
Rails.application.routes.draw do
  get 'favourites/update'
  root 'home#index'

  resources :properties do
    member do
      get :approve
    end
    # collection do
    #   patch 'approve'
    # end
    resources :reviews
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :categories, except: [:show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'properties/approve_property'
  # post 'properties/:id', to: 'properties#approve'
# delete 'sign_out', to: "sessions#destroy", as: 'sign_out'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  after_validation { self.name = self.name.capitalize }
  validates :name, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :property
  belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_one_attached :property_image
  has_many :reviews, dependent: :destroy

  after_validation { self.city = self.city.upcase }

  validates :address, presence: true, length: {minimum: 10, maximum: 255}
  validates :Price, presence: true, numericality: true
  validates :Area, presence: true, numericality: true
  validates :OwnerName, presence: true, length: {minimum: 3, maximum: 50}
  validates :ContactPerson, presence: true, length: {minimum: 3, maximum: 50}
  validates :Number, presence: true, numericality: true, length: { is: 10 }
  validates :city, presence: true
  validates :property_status, presence: true
end
# y(id: integer, PropertyType: string, address: string, Price: float, Area: float,
#    OwnerName: string,
#    ContactPerson: string, Number: integer, user_id: integer,
#    created_at: datetime, updated_at: datetime,
#     city: string, property_status: string, approved_status: boolean,
#      rejection_reason: string)

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :property
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  has_many :properties, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites

  after_validation { self.email = self.email.downcase }

  validates :username, presence: true, length: { maximum: 25 }, uniqueness: { case_sensetive: false }
  validates :email, presence: true, length: { maximum: 25 }, uniqueness: { case_sensetive: false }, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end
  def new
    @category = Category.new
  end
  def edit
    @category = Category.find(params[:id])
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category is Add Successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category is Updated Successfully"

      redirect_to categories_path
    else
      render 'edit'
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] = "Category is Deleted"

    redirect_to categories_path
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def update
    favourite = Favourite.where(property: Property.find(params[:property]), user: current_user)
    if favourite == []
      Favourite.create(property: Property.find(params[:property]), user: current_user)
      @favourite_exists = true
    else
      favourite.destroy_all
      @favourite_exists = false
    end
    redirect_to property_path(Property.find(params[:property]))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @property_first = Property.first(3)
    @property_last = Property.order("created_at DESC").last(3)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.create(review_params)
    @review.user_id = current_user.id
    @review.save

    redirect_to property_path(@property)
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in Successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end


  def edit
    
  end

  def show

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "BOOYAH #{@user.username}"
      redirect_to properties_path
    else
      render 'new'
    end
  end

  def update

    if @user.update(user_params)
      flash[:notice] = 'ACCOUNT IS UPDATED'
      redirect_to properties_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  def set_user
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to image_tag("icon.png", size: "90x40", alt: "Edit Entry"), root_path, class: "navbar-brand"%>
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class:'nav-link'%>
        </li>
        <% if logged_in? %>
          <li class="nav-item active">
            <%= link_to 'All Properties', properties_path, class:'nav-link'%>
          </li>
          <% unless admin? %>
            <li class="nav-item active">
              <%= link_to 'Post property', new_property_path, class:'nav-link'%>
            </li>
          <% end %>
        <% end %>
        <% if admin? %>
          <li class="nav-item active">
            <%= link_to 'Approve Properties', new_category_path, class:'nav-link'%>
          </li>
          <li class="nav-item active">
            <%= link_to 'All categories', categories_path, class:'nav-link'%>
          </li>
          <li class="nav-item active">
            <%= link_to 'Add Category', new_category_path, class:'nav-link'%>
          </li>

        <% end %>
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
                <%= link_to current_user.username, user_path(current_user), class: "dropdown-item"%>
                      <div class="dropdown-divider"></div>
                <%= link_to 'Log out', logout_path, class: "dropdown-item", method: :delete%>
            <% else %>
                <%= link_to 'SignUp', signup_path, class: "dropdown-item"%>
                <%= link_to 'Log In', login_path, class: "dropdown-item"%>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commomfloor01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>